/*
 * This source file was generated by the Gradle 'init' task
 */

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		TokenArray t = (TokenArray) ExpressionUtils.tokenizer("((123+321)*22)-11111").get();

		double d = ExpressionUtils.collapser(t.value).value;

		System.out.println(new App().getGreeting());
	}
}
