
/*
 * This source file was generated by the Gradle 'init' task
 */
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
  @Test
  void isNumberTest() {
    assertEquals((new Cell("1")).isNumberFix(), true);
    assertEquals((new Cell("-1.1")).isNumberFix(), true);
    assertEquals((new Cell("1.2")).isNumberFix(), true);
    assertEquals((new Cell("-3.1")).isNumberFix(), true);

    assertEquals((new Cell("1+2*3")).isNumberFix(), false);
    assertEquals((new Cell("(1+2)")).isNumberFix(), false);
    assertEquals((new Cell("a")).isNumberFix(), false);
    assertEquals((new Cell("AB")).isNumberFix(), false);
    assertEquals((new Cell("@2")).isNumberFix(), false);
    assertEquals((new Cell("2+)")).isNumberFix(), false);
    assertEquals((new Cell("(3+1*2)-")).isNumberFix(), false);
    assertEquals((new Cell("2a")).isNumberFix(), false);
    assertEquals((new Cell("{2}")).isNumberFix(), false);
    assertEquals((new Cell("hi")).isNumberFix(), false);

    assertEquals((new Cell("=1")).isNumberFix(), false);
    assertEquals((new Cell("=1+2*2")).isNumberFix(), false);
    assertEquals((new Cell("=(1+2)*2")).isNumberFix(), false);
    assertEquals((new Cell("=((1+2)*2)-1")).isNumberFix(), false);
    assertEquals((new Cell("=1.2")).isNumberFix(), false);
    assertEquals((new Cell("=-3.1")).isNumberFix(), false);
    assertEquals((new Cell("=(0.2)")).isNumberFix(), false);
    assertEquals((new Cell("=1+2")).isNumberFix(), false);
    assertEquals((new Cell("=1+2*3")).isNumberFix(), false);
  }

  @Test
  void isTextTest() {
    assertEquals((new Cell("1")).isTextFix(), false);
    assertEquals((new Cell("-1.1")).isTextFix(), false);
    assertEquals((new Cell("1.2")).isTextFix(), false);
    assertEquals((new Cell("-3.1")).isTextFix(), false);

    assertEquals((new Cell("1+2*3")).isTextFix(), true);
    assertEquals((new Cell("(1+2)")).isTextFix(), true);
    assertEquals((new Cell("a")).isTextFix(), true);
    assertEquals((new Cell("AB")).isTextFix(), true);
    assertEquals((new Cell("@2")).isTextFix(), true);
    assertEquals((new Cell("2+)")).isTextFix(), true);
    assertEquals((new Cell("(3+1*2)-")).isTextFix(), true);
    assertEquals((new Cell("2a")).isTextFix(), true);
    assertEquals((new Cell("{2}")).isTextFix(), true);
    assertEquals((new Cell("hi")).isTextFix(), true);

    assertEquals((new Cell("=1")).isTextFix(), false);
    assertEquals((new Cell("=1+2*2")).isTextFix(), false);
    assertEquals((new Cell("=(1+2)*2")).isTextFix(), false);
    assertEquals((new Cell("=((1+2)*2)-1")).isTextFix(), false);
    assertEquals((new Cell("=1.2")).isTextFix(), false);
    assertEquals((new Cell("=-3.1")).isTextFix(), false);
    assertEquals((new Cell("=(0.2)")).isTextFix(), false);
    assertEquals((new Cell("=1+2")).isTextFix(), false);
    assertEquals((new Cell("=1+2*3")).isTextFix(), false);
  }

  @Test
  void isFormTest() {
    assertEquals((new Cell("1")).isFormFix(), false);
    assertEquals((new Cell("-1.1")).isFormFix(), false);
    assertEquals((new Cell("1.2")).isFormFix(), false);
    assertEquals((new Cell("-3.1")).isFormFix(), false);

    assertEquals((new Cell("1+2*3")).isFormFix(), false);
    assertEquals((new Cell("(1+2)")).isFormFix(), false);
    assertEquals((new Cell("a")).isFormFix(), false);
    assertEquals((new Cell("AB")).isFormFix(), false);
    assertEquals((new Cell("@2")).isFormFix(), false);
    assertEquals((new Cell("2+)")).isFormFix(), false);
    assertEquals((new Cell("(3+1*2)-")).isFormFix(), false);
    assertEquals((new Cell("2a")).isFormFix(), false);
    assertEquals((new Cell("{2}")).isFormFix(), false);
    assertEquals((new Cell("hi")).isFormFix(), false);

    assertEquals((new Cell("=1")).isFormFix(), true);
    assertEquals((new Cell("=1+2*2")).isFormFix(), true);
    assertEquals((new Cell("=(1+2)*2")).isFormFix(), true);
    assertEquals((new Cell("=((1+2)*2)-1")).isFormFix(), true);
    assertEquals((new Cell("=1.2")).isFormFix(), true);
    assertEquals((new Cell("=-3.1")).isFormFix(), true);
    assertEquals((new Cell("=(0.2)")).isFormFix(), true);
    assertEquals((new Cell("=1+2")).isFormFix(), true);
    assertEquals((new Cell("=1+2*3")).isFormFix(), true);
  }

  @Test
  void evalTest() {
    Spreadsheet spreadsheet = new Spreadsheet(10, 1);

    spreadsheet.set(0, 0, new Cell("=1+2*2"));
    assertEquals(spreadsheet.eval(0, 0), "5.0");

    spreadsheet.set(1, 0, new Cell("=1"));
    assertEquals(spreadsheet.eval(1, 0), "1.0");

    spreadsheet.set(2, 0, new Cell("=1.2"));
    assertEquals(spreadsheet.eval(2, 0), "1.2");

    spreadsheet.set(3, 0, new Cell("=(1+2)*2"));
    assertEquals(spreadsheet.eval(3, 0), "6.0");

    spreadsheet.set(4, 0, new Cell("=-3.1"));
    assertEquals(spreadsheet.eval(4, 0), "-3.1");

    spreadsheet.set(5, 0, new Cell("=((1+2)*2)-1"));
    assertEquals(spreadsheet.eval(5, 0), "5.0");

    spreadsheet.set(6, 0, new Cell("=(0.2)"));
    assertEquals(spreadsheet.eval(6, 0), "0.2");

    spreadsheet.set(7, 0, new Cell("=1+2*3"));
    assertEquals(spreadsheet.eval(7, 0), "7.0");

    spreadsheet.set(8, 0, new Cell("=((123+321)*22)-11111"));
    assertEquals(spreadsheet.eval(8, 0), "-1343.0");
  }

  @Test
  void depthTest() {
    Spreadsheet spreadsheet = new Spreadsheet(13, 1);

    spreadsheet.set(0, 0, new Cell("=1+2*2"));
    assertEquals(spreadsheet.depthOne(0, 0), 1);

    spreadsheet.set(1, 0, new Cell("=1"));
    assertEquals(spreadsheet.depthOne(1, 0), 1);

    spreadsheet.set(2, 0, new Cell("=1.2"));
    assertEquals(spreadsheet.depthOne(2, 0), 1);

    spreadsheet.set(3, 0, new Cell("=(1+2)*2"));
    assertEquals(spreadsheet.depthOne(3, 0), 2);

    spreadsheet.set(4, 0, new Cell("=-3.1"));
    assertEquals(spreadsheet.depthOne(4, 0), 1);

    spreadsheet.set(5, 0, new Cell("=((1+2)*2)-1"));
    assertEquals(spreadsheet.depthOne(5, 0), 3);

    spreadsheet.set(6, 0, new Cell("=(0.2)"));
    assertEquals(spreadsheet.depthOne(6, 0), 2);

    spreadsheet.set(7, 0, new Cell("=1+2*3"));
    assertEquals(spreadsheet.depthOne(7, 0), 1);

    spreadsheet.set(8, 0, new Cell("=((123+321)*22)-11111"));
    assertEquals(spreadsheet.depthOne(8, 0), 3);

    spreadsheet.set(9, 0, new Cell("=a"));
    assertEquals(spreadsheet.depthOne(9, 0), -1);

    spreadsheet.set(9, 0, new Cell("=AB"));
    assertEquals(spreadsheet.depthOne(9, 0), -1);

    spreadsheet.set(9, 0, new Cell("=@2"));
    assertEquals(spreadsheet.depthOne(9, 0), -1);

    spreadsheet.set(9, 0, new Cell("=2+"));
    assertEquals(spreadsheet.depthOne(9, 0), -1);

    spreadsheet.set(9, 0, new Cell("=(3+1*2)-"));
    assertEquals(spreadsheet.depthOne(9, 0), -1);

    spreadsheet.set(10, 0, new Cell("=1..0"));
    assertEquals(spreadsheet.depthOne(10, 0), -1);

    spreadsheet.set(11, 0, new Cell("=(1..0+57)"));
    assertEquals(spreadsheet.depthOne(11, 0), -1);

    spreadsheet.set(12, 0, new Cell("=(1..0+57)*7.5"));
    assertEquals(spreadsheet.depthOne(12, 0), -1);
  }
}
